using System;


namespace ReputationCalc.Models
{
    // Autogenerated Class by MS Visual Studio
    public class ErrorViewModel
    {
        // Autogenerated code by MS Visual Studio
        public string RequestId { get; set; }
        
        // Autogenerated code by MS Visual Studio
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}